Repository interledger4j/ilpv4-connector, pull requests merged in 2019-11, with the labels that each got.

#393 Create SECURITY.md
  SECURITY.md
Labels: security

#394 Update SECURITY.md
  SECURITY.md
Labels: security

#392 Add Prometheus metrics to Connector (Fixes #146)
  connector-core/src/main/java/org/interledger/connector/core/events/ConnectorEvent.java
  connector-core/src/main/java/org/interledger/connector/core/settlement/SettlementQuantity.java
  connector-it/src/test/java/org/interledger/connector/it/settlement/TwoConnectorXrpSettlementIT.java
  connector-link/pom.xml
  connector-link/src/main/java/org/interledger/connector/link/http/AbstractBlastHttpSender.java
  connector-link/src/main/java/org/interledger/connector/link/http/JwtBlastHttpSender.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/blast/IlpOverHttpAuthenticationProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/blast/JwtHs256AuthenticationProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/settlement/SettlementController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/javamoney/JavaMoneyConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/metrics/MetricsConfiguration.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/main/resources/application-dev.yml
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AbstractControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/settlement/SettlementControllerTest.java
  connector-service-api/src/main/java/org/interledger/connector/ILPv4Connector.java
  connector-service-api/src/main/java/org/interledger/connector/events/ConnectorEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/IncomingSettlementFailedEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/IncomingSettlementSucceededEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/LocalSettlementProcessedEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/OutgoingSettlementInitiationFailedEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/OutgoingSettlementInitiationSucceededEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/SettlementInitiatedEvent.java
  connector-service-api/src/main/java/org/interledger/connector/metrics/MetricsService.java
  connector-service-api/src/main/java/org/interledger/connector/settlement/SettlementService.java
  connector-service-impl/pom.xml
  connector-service-impl/src/main/java/org/interledger/connector/balances/RedisBalanceTracker.java
  connector-service-impl/src/main/java/org/interledger/connector/caching/AccountSettingsLoadingCache.java
  connector-service-impl/src/main/java/org/interledger/connector/config/CaffeineCacheConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/javax/money/providers/CryptoCompareRateProvider.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/AbstractLinkFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/OutgoingBalanceLinkFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/OutgoingMetricsLinkFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/metrics/PrometheusCollectors.java
  connector-service-impl/src/main/java/org/interledger/connector/metrics/PrometheusMetricsService.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/BalanceIlpPacketFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/PacketMetricsFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/RateLimitIlpPacketFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/settlement/DefaultSettlementService.java
  connector-service-impl/src/test/java/org/interledger/connector/javax/money/providers/CryptoCompareRateProviderTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/filters/OutgoingBalanceLinkFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/filters/OutgoingMaxPacketAmountLinkFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/filters/OutgoingMetricsLinkFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/metrics/PrometheusMetricsServiceTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/MaxPacketAmountFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/PacketMetricsFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/RateLimitIlpPacketFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/settlement/DefaultSettlementServiceTest.java
  pom.xml
Labels: enhancement, monitoring

#417 Start running test in the sever module
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java
  connector-server/src/test/java/org/interledger/connector/server/javamoney/AdminApiSecurityTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-server/src/test/resources/application-test.yml
Labels: accounts, security, test-coverage, v0.1.0

#412 Fixes #391
  connector-it/src/test/resources/application.yml
  connector-server/src/main/resources/application-migrate-only.yml
  connector-server/src/main/resources/application-postgres.yml
  connector-server/src/main/resources/application-spsp_dev.yml
Labels: cleanup, configuration, v0.1.0

#418 Df/fixes 363
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultNextHopPacketMapperTest.java
Labels: test-coverage, v0.1.0

#422 Condense IL-DCP config properties into a single property (fixes #378)
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorParentChildBlastTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerBlastTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-model/src/main/java/org/interledger/connector/settings/EnabledProtocolSettings.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/EnabledProtocolSettingsFromPropertyFile.java
  connector-server/src/main/resources/application.yml
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java
  connector-server/src/test/resources/application-connector-unit-test.yml
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/PeerProtocolPacketFilter.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/PeerProtocolPacketFilterTest.java
Labels: accounts, cleanup, configuration, v0.1.0

#424 use h2 in-memory mode in spring tests
  connector-server/src/main/resources/application-h2.yml
  connector-server/src/test/resources/application-test.yml
Labels: v0.1.0

#406 Is/routes admin api
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topology/nodes/ConnectorServerNode.java
  connector-it/src/test/resources/initialization.sql
  connector-jackson/pom.xml
  connector-jackson/src/main/java/org/interledger/connector/jackson/ObjectMapperFactory.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/modules/InterledgerAddressPrefixDeserializer.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/modules/InterledgerAddressPrefixModule.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/modules/InterledgerAddressPrefixSerializer.java
  connector-model/src/main/java/org/interledger/connector/StaticRoute.java
  connector-model/src/main/java/org/interledger/connector/settings/GlobalRoutingSettings.java
  connector-persistence/pom.xml
  connector-persistence/src/main/java/org/interledger/connector/persistence/config/ConvertersConfig.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/converters/StaticRouteEntityConverter.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DataConstants.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/StaticRouteEntity.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/StaticRoutesRepository.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/StaticRoutesRepositoryCustom.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/StaticRoutesRepositoryImpl.java
  connector-persistence/src/main/resources/db/changelogs/base/changelog.xml
  connector-persistence/src/test/java/org/interledger/connector/persistence/converters/StaticRouteEntityConverterTest.java
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/StaticRoutesRepositoryTest.java
  connector-routing-api/pom.xml
  connector-routing-api/src/main/java/org/interledger/connector/routing/ExternalRoutingService.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/Route.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/RoutingTable.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRoute.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRouteAlreadyExistsProblem.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRouteNotFoundProblem.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRouteProblem.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRouteUnprocessableProblem.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRoutesManager.java
  connector-routing-impl/pom.xml
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryExternalRoutingService.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/NoOpExternalRoutingService.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/InMemoryExternalRoutingServiceTest.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/PathConstants.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/StaticRoutesController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorSettingsFromPropertyFile.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/StaticRouteFromPropertyFile.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SpringConnectorWebMvc.java
  connector-server/src/main/resources/application-blast_dev.yml
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtHs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/StaticRoutesSpringBootTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java
  connector-server/src/test/resources/application-connector-unit-test.yml
  connector-server/src/test/resources/application-test.yml
  connector-service-api/src/main/java/org/interledger/connector/ILPv4Connector.java
  connector-service-impl/pom.xml
  connector-service-impl/src/main/java/org/interledger/connector/DefaultILPv4Connector.java
Labels: configuration, v0.1.0

#425 Fixes #390
  connector-model/pom.xml
  connector-model/src/main/java/org/interledger/connector/StaticRoute.java
  connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java
  connector-model/src/test/java/org/interledger/connector/settings/ConnectorSettingsTest.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryExternalRoutingService.java
  connector-server/src/main/resources/application-dev.yml
Labels: configuration, v0.1.0

#428 Fixes #403
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/StaticRoutesController.java
  connector-server/src/main/resources/application-dev.yml
Labels: configuration, v0.1.0

#427 Fix Problem JSON Status code serialization (Fixes #402)
  connector-accounts/pom.xml
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccountSettings.java
  connector-accounts/src/test/java/org/interledger/connector/accounts/AccountBalanceSettingsTest.java
  connector-accounts/src/test/java/org/interledger/connector/accounts/AccountRelationshipTest.java
  connector-core/pom.xml
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorParentChildIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-it/src/test/java/org/interledger/connector/it/ilpoverhttp/TwoConnectorMixedAssetCodeTestIT.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/ObjectMapperFactory.java
  connector-jackson/src/test/java/org/interledger/connector/jackson/model/AccountBalanceSettingsJsonTest.java
  connector-jackson/src/test/java/org/interledger/connector/jackson/model/AccountSettingsJsonTest.java
  connector-jackson/src/test/java/org/interledger/connector/jackson/model/AccountSettingsTest.java
  connector-jackson/src/test/java/org/interledger/connector/jackson/modules/ProblemSerializerTest.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/converters/AccountSettingsEntityConverter.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/AccountSettingsEntity.java
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/AccountSettingsRepositoryTest.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SpringConnectorWebMvc.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AbstractControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/ControllerConfig.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/ControllerTestConfig.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/settlement/SettlementControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/web/SpringConnectorWebMvcTest.java
  connector-service-api/src/main/java/org/interledger/connector/settlement/client/CreateSettlementAccountRequest.java
  connector-service-api/src/main/java/org/interledger/connector/settlement/client/SendMessageRequest.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/OutgoingMaxPacketAmountLinkFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/MaxPacketAmountFilter.java
  connector-service-impl/src/test/java/org/interledger/connector/links/filters/OutgoingMaxPacketAmountLinkFilterTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/MaxPacketAmountFilterTest.java
  pom.xml
Labels: accounts, bug, v0.1.0

#434 Allow Account Settings admin API to accept plain-text secret values
  connector-model/src/main/java/org/interledger/connector/settings/ConnectorKey.java
  connector-model/src/main/java/org/interledger/connector/settings/ConnectorKeys.java
  connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java
  connector-model/src/test/java/org/interledger/connector/settings/ConnectorSettingsTest.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/Redactor.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/GcpCryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/JksCryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/link/IlpOverHttpConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorKeyFromPropertyFile.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorKeysFromPropertyFile.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorSettingsFromPropertyFile.java
  connector-server/src/main/resources/application-dev.yml
  connector-server/src/main/resources/application.yml
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorAdminClient.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtHs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/SimpleIlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProviderTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/RedactorTest.java
  connector-server/src/test/resources/application-connector-unit-test.yml
  connector-service-api/pom.xml
  connector-service-api/src/main/java/org/interledger/connector/crypto/ConnectorEncryptionService.java
  connector-service-api/src/main/java/org/interledger/connector/links/LinkSettingsValidator.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/crypto/DefaultConnectorEncryptionService.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkSettingsValidator.java
  connector-service-impl/src/test/java/org/interledger/connector/accounts/DefaultAccountManagerTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsValidatorTest.java
  pom.xml
Labels: accounts, v0.1.0

#430 Fixes #407
  connector-core/src/main/java/org/interledger/connector/core/ConfigConstants.java
  connector-it/src/test/java/org/interledger/connector/it/AbstractIlpOverHttpIT.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/link/IlpOverHttpConfig.java
  connector-server/src/main/resources/application-blast_dev.yml
  connector-server/src/main/resources/application-dev.yml
  connector-server/src/main/resources/application.yml
  connector-server/src/test/resources/application-connector-unit-test.yml
Labels: accounts, configuration, v0.1.0

#429 Df/277 fix health endpoint
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/HealthController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/PathConstants.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/main/resources/application-h2.yml
  connector-server/src/main/resources/application-management.yml
  connector-server/src/main/resources/application.yml
Labels: configuration, security, v0.1.0

#441 Df/431 add swagger
  connector-routing-api/src/main/java/org/interledger/connector/routing/Route.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/StaticRoute.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/StaticRoutesSpringBootTest.java
  connector-server/swagger/README.md
  connector-server/swagger/connector-admin-open-api3.yaml
Labels: v0.1.0

#448 delete accounts part deux #171
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DataConstants.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DeletedAccountSettingsEntity.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/DeletedAccountSettingsRepository.java
  connector-persistence/src/main/resources/db/changelogs/base/changelog.xml
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/DeletableAccountSettingsRepositoryTest.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorAdminClient.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-service-api/src/main/java/org/interledger/connector/accounts/AccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/test/java/org/interledger/connector/accounts/DefaultAccountManagerTest.java
Labels: accounts, v0.1.0

#446 Stream fulfillments to GCP
  connector-it/pom.xml
  connector-it/src/test/java/org/interledger/connector/it/AbstractIlpOverHttpIT.java
  connector-it/src/test/java/org/interledger/connector/it/ContainerHelper.java
  connector-it/src/test/java/org/interledger/connector/it/ilpoverhttp/TwoConnectorMixedAssetCodeTestIT.java
  connector-it/src/test/java/org/interledger/connector/it/pubsub/PubSubResourceGenerator.java
  connector-it/src/test/resources/application.yml
  connector-jackson/src/main/java/org/interledger/connector/jackson/ObjectMapperFactory.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpSender.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/CcpSenderReceiverTest.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/gcp/GcpPubSubConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/resources/application-gcp-pubsub.yml
  connector-server/src/main/resources/application.yml
  connector-service-api/src/main/java/org/interledger/connector/events/PacketFulfillmentEvent.java
  connector-service-api/src/main/java/org/interledger/connector/gcp/FulfillmentPublisher.java
  connector-service-api/src/main/java/org/interledger/connector/gcp/GcpFulfillmentEvent.java
  connector-service-api/src/main/java/org/interledger/connector/links/NextHopInfo.java
  connector-service-api/src/main/java/org/interledger/connector/links/NextHopPacketMapper.java
  connector-service-impl/pom.xml
  connector-service-impl/src/main/java/org/interledger/connector/connections/SimulatedBppConnection.java
  connector-service-impl/src/main/java/org/interledger/connector/gcp/DefaultFulfillmentPublisher.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/AbstractLinkFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/OutgoingBalanceLinkFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitch.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChain.java
  connector-service-impl/src/test/java/org/interledger/connector/gcp/DefaultFulfillmentPublisherTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitchTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChainTest.java
  pom.xml
Labels: settlement, v0.1.0

#462 Fixes #261
  README.md
Labels: documentation, v0.1.0

#463 Is/459 fix simple auth
  connector-accounts/src/main/java/org/interledger/connector/accounts/Ids.java
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProvider.java
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorAdminClient.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtHs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/SimpleIlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProviderTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkSettingsValidator.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsValidatorTest.java
Labels: v0.1.0

#466 Df/move emitter to quilt
  connector-core/src/main/java/org/interledger/connector/core/Ilpv4Constants.java
  connector-server/pom.xml
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/IlpOverHttpJwtEmitter.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/IlpPacketEmitter.java
Labels: cleanup, v0.2.0
