Repository interledger4j/ilpv4-connector, pull requests merged in 2019-10, with the labels that each got.

#326 upgrade to Quilt 1.0.0
  connector-it/src/test/java/org/interledger/connector/it/AbstractBlastIT.java
  connector-it/src/test/java/org/interledger/connector/it/blast/TwoConnectorBlastPingTestIT.java
  connector-it/src/test/java/org/interledger/connector/it/blast/TwoConnectorIldcpTestIT.java
  connector-it/src/test/java/org/interledger/connector/it/settlement/TwoConnectorXrpSettlementIT.java
  connector-link/src/main/java/org/interledger/connector/link/PingableLink.java
  connector-link/src/test/java/org/interledger/connector/link/CircuitBreakingLinkTest.java
  connector-routing-api/pom.xml
  connector-routing-api/src/main/java/org/interledger/connector/ccp/codecs/AsnCcpRouteCodec.java
  connector-routing-api/src/main/java/org/interledger/connector/ccp/codecs/AsnCcpRoutePathPartCodec.java
  connector-routing-api/src/main/java/org/interledger/connector/ccp/codecs/AsnCcpRouteUpdateRequestCodec.java
  connector-routing-api/src/main/java/org/interledger/connector/ccp/codecs/AsnCcpWithdrawnRouteCodec.java
  connector-routing-api/src/test/java/org/interledger/connector/ccp/codecs/AbstractAsnCodecTest.java
  connector-routing-api/src/test/java/org/interledger/connector/ccp/codecs/IlpCcpNewRouteControlRequestCodecTest.java
  connector-routing-api/src/test/java/org/interledger/connector/ccp/codecs/IlpCcpNewRouteUpdateRequestCodecTest.java
  connector-routing-impl/pom.xml
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpReceiver.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpSender.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/CcpSenderReceiverTest.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/CodecContextConfig.java
  connector-server/src/test/java/org/interledger/connector/server/ilphttp/IlpPacketEmitter.java
  connector-server/src/test/java/org/interledger/connector/server/ilphttp/JwtBlastEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/converters/OerPreparePacketHttpMessageConverterTest.java
  connector-service-impl/pom.xml
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/main/java/org/interledger/connector/settlement/DefaultSettlementService.java
  connector-service-impl/src/test/java/org/interledger/connector/links/ping/PingLoopbackLinkTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitchTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChainTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/PeerProtocolPacketFilterTest.java
  pom.xml
Labels: cleanup, enhancement, v0.2.0

#330 Fixes dependabot PRs
  connector-link/src/test/java/org/interledger/connector/link/CircuitBreakingLinkTest.java
  connector-persistence/pom.xml
  pom.xml
Labels: cleanup, dependencies, v0.1.0

#333 Fix dependabot problems…
  connector-crypto/connector-crypto-cli/pom.xml
  pom.xml
Labels: dependencies, v0.1.0

#335 configure Jackson to ignore unknown properties
  connector-jackson/src/main/java/org/interledger/connector/jackson/ObjectMapperFactory.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/JacksonConfig.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
Labels: v0.1.0

#351 serialize numbers as numbers except for specific amount fields (to appease node.js settlement api)
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccountSettings.java
  connector-core/src/main/java/org/interledger/connector/core/problems/AbstractConnectorProblem.java
  connector-core/src/test/java/org/interledger/connector/core/settlement/SettlementQuantityTest.java
  connector-jackson/pom.xml
  connector-jackson/src/test/java/org/interledger/connector/jackson/model/AccountSettingsTest.java
  connector-jackson/src/test/java/org/interledger/connector/jackson/modules/ProblemSerializerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-service-api/src/main/java/org/interledger/connector/settlement/client/InitiateSettlementRequest.java
  connector-service-api/src/main/java/org/interledger/connector/settlement/client/InitiateSettlementResponse.java
  connector-service-api/src/test/java/org/interledger/connector/settlement/client/InitiateSettlementRequestTest.java
Labels: configuration, v0.1.0

#375 use okhttp in JavaMoneyConfig (for CryptoCompare)
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/javamoney/JavaMoneyConfig.java
  connector-server/src/test/java/org/interledger/connector/server/javamoney/JavaMoneyConfigTest.java
  connector-server/src/test/resources/application-test.yml
Labels: Performance, enhancement, v0.1.0
