Repository interledger4j/ilpv4-connector, pull requests merged in 2020-03, with the labels that each got.

#609 Add SentryConfig to Connector.
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/resources/application.yml
  connector-server/src/main/resources/logback-gcp.xml
  connector-server/src/main/resources/logback-spring.xml
  connector-service-impl/src/main/java/org/interledger/connector/DefaultILPv4Connector.java
  pom.xml
Labels: configuration

#611 [WIP] initial pass at implement account access tokens
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccessToken.java
  connector-accounts/src/main/java/org/interledger/connector/accounts/event/AccountCredentialsUpdatedEvent.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/config/ConnectorPersistenceConfig.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/config/ConvertersConfig.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/converters/AccessTokenEntityConverter.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/AccessTokenEntity.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DataConstants.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/package-info.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/AccessTokensRepository.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/AccessTokensRepositoryCustom.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/AccessTokensRepositoryImpl.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/types/AccountIdType.java
  connector-persistence/src/main/resources/db/changelog-master.xml
  connector-persistence/src/main/resources/db/changelogs/base/changelog_00001_access_token.xml
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/AccessTokensRepositoryTest.java
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/PathConstants.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/account/AccountAccessTokenController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SpringConnectorWebMvc.java
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorUserClient.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProviderTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AbstractControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AccountBalanceSpringBootTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/IlpHttpControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/account/AccountAccessTokenSpringBootTest.java
  connector-service-api/src/main/java/org/interledger/connector/accounts/AccessTokenManager.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccessTokenManager.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/test/java/org/interledger/connector/accounts/DefaultAccessTokenManagerTest.java
Labels: accounts, security

#616 fix bug in CCP route updates that would cause routes updates to be lost due to epoch not being incremented
  connector-routing-api/src/main/java/org/interledger/connector/routing/ForwardingRoutingTable.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpSender.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryExternalRoutingService.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryForwardingRoutingTable.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/CcpSenderReceiverTest.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/InMemoryForwardingRoutingTableTest.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/InMemoryRoutingTableTest.java
Labels: bug, routing

#618 add ETH as a currency
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/javamoney/JavaMoneyConfig.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtRs256IlpOverHttpEndpointTest.java
  connector-service-impl/src/main/java/org/interledger/connector/javax/money/providers/EthCurrencyProvider.java
  connector-service-impl/src/test/java/org/interledger/connector/javax/money/providers/EthCurrencyProviderTest.java
  connector-service-impl/src/test/java/org/interledger/connector/javax/money/providers/MonetaryTest.java
  connector-service-impl/src/test/resources/META-INF/services/javax.money.spi.CurrencyProviderSpi
Labels: enhancement, fx

#620 Df/validate xrp rounding
  connector-service-impl/src/main/java/org/interledger/connector/javax/money/providers/DropRoundingProvider.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/test/java/org/interledger/connector/fx/JavaMoneyUtilsTest.java
  connector-service-impl/src/test/java/org/interledger/connector/javax/money/providers/DropRoundingProviderTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultNextHopPacketMapperTest.java
Labels: fx

#626 Deprecate invalid ILP-over-HTTP Content-Type header (Fixes #586)
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/IlpHttpController.java
Labels: cleanup
