Repository interledger4j/ilpv4-connector, pull requests merged in 2020-04, with the labels that each got.

#624 Cleanup & Enforce AccountId Requirements (Fixes #623)
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccountNotFoundProblem.java
  connector-accounts/src/main/java/org/interledger/connector/accounts/Ids.java
  connector-accounts/src/main/java/org/interledger/connector/accounts/InvalidAccountIdProblem.java
  connector-accounts/src/main/java/org/interledger/connector/accounts/sub/LocalDestinationAddressUtils.java
  connector-accounts/src/test/java/org/interledger/connector/accounts/AccountIdTest.java
  connector-accounts/src/test/java/org/interledger/connector/accounts/sub/LocalDestinationAddressUtilsTest.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/AccountSettingsEntity.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/DataConstants.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/StaticRouteEntity.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/repositories/AccountSettingsRepositoryImpl.java
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/AccountSettingsRepositoryTest.java
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/FilterAccountByValidAccountIdTest.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/AccountBalanceController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/IlpHttpController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/ProblemExceptionHandling.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/account/AccountAccessTokenController.java
  connector-service-impl/src/main/java/org/interledger/connector/DefaultILPv4Connector.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/balances/AccountBalanceService.java
  connector-service-impl/src/test/java/org/interledger/connector/settlement/DefaultSettlementServiceTest.java
Labels: accounts, bug

#628 Update Quilt to latest v1.2.0
  pom.xml
Labels: dependencies

#627 invalidate account settings cache on update
  .circleci/config.yml
  connector-accounts/src/main/java/org/interledger/connector/accounts/sub/LocalDestinationAddressUtils.java
  connector-accounts/src/test/java/org/interledger/connector/accounts/sub/LocalDestinationAddressUtilsTest.java
  connector-it/pom.xml
  connector-it/src/main/java/org/interledger/connector/it/markers/Coordination.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorClusterTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorParentChildIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topology/AbstractBaseTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topology/ClusteredTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topology/Edge.java
  connector-it/src/main/java/org/interledger/connector/it/topology/Topology.java
  connector-it/src/test/java/org/interledger/connector/it/AbstractIlpOverHttpIT.java
  connector-it/src/test/java/org/interledger/connector/it/DefaultTestSuite.java
  connector-it/src/test/java/org/interledger/connector/it/coordination/TwoConnectorAccountCoordinationIT.java
  connector-it/src/test/java/org/interledger/connector/it/coordination/package-info.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/AccountSettingsEntity.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/entities/StaticRouteEntity.java
  connector-persistence/src/test/java/org/interledger/connector/persistence/repositories/AccountSettingsRepositoryTest.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/RedisPubSubConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/ProblemExceptionHandling.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/resources/application-dev-behind-hermes.yml
  connector-service-api/src/main/java/org/interledger/connector/ILPv4Connector.java
  connector-service-impl/src/main/java/org/interledger/connector/DefaultILPv4Connector.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/caching/AccountSettingsLoadingCache.java
  connector-service-impl/src/main/java/org/interledger/connector/config/CaffeineCacheConfig.java
  connector-service-impl/src/test/java/org/interledger/connector/caching/AccountSettingsLoadingCacheTest.java
  connector-service-impl/src/test/java/org/interledger/connector/settlement/DefaultSettlementServiceTest.java
Labels: accounts, bug

#630 bug fixes for local spsp fulfillment:
  connector-model/src/main/java/org/interledger/connector/settings/SpspSettings.java
  connector-server/src/main/java/org/interledger/connector/server/wallet/controllers/SpspController.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/wallet/controllers/SpspControllerWithNoPathSpringTest.java
  connector-server/src/test/resources/application-test.yml
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFile.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/EnabledFeatureSettingsFromPropertyFile.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/EnabledProtocolSettingsFromPropertyFile.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/SpspSettingsFromPropertyFile.java
  connector-service-impl/src/test/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFileTest.java
  connector-service-impl/src/test/resources/application-connector-unit-test.yml
Labels: accounts, bug

#634 Use an executor service for spawning tasks to send packets
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/DefaultLinkFilterChain.java
Labels: Performance, enhancement

#641 Enable CSP
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
Labels: accounts, security

#639 Remove unused SignatureService
  connector-crypto/src/main/java/org/interledger/crypto/SignatureAlgorithm.java
  connector-crypto/src/main/java/org/interledger/crypto/SignatureException.java
  connector-crypto/src/main/java/org/interledger/crypto/SignatureService.java
  connector-crypto/src/main/java/org/interledger/crypto/SignatureSigner.java
  connector-crypto/src/main/java/org/interledger/crypto/SignatureVerifier.java
  connector-crypto/src/main/java/org/interledger/crypto/impl/SharedSecretSignatureService.java
Labels: cleanup

#640 Improve server startup logging
  connector-crypto/src/main/java/org/interledger/crypto/KeyStoreType.java
  connector-crypto/src/main/java/org/interledger/crypto/impl/DelegatingEncryptionService.java
  connector-model/src/main/java/org/interledger/connector/RuntimeProperties.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/RedisPubSubConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/CryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/GcpCryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/JksCryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/IdempotenceCacheConfig.java
  connector-server/src/main/resources/application-dev.yml
  connector-server/src/main/resources/application-local-spsp-fulfillment.yml
  connector-server/src/main/resources/application-packet-switch-mode.yml
  connector-server/src/main/resources/application-wallet-mode.yml
  connector-server/src/main/resources/application.yml
  connector-server/src/main/resources/banner-dev-mode.txt
  connector-server/src/main/resources/banner-packet-switch-mode.txt
  connector-server/src/main/resources/banner-wallet-mode.txt
  connector-server/src/test/resources/application-test.yml
  connector-service-impl/src/main/java/org/interledger/connector/config/BalanceTrackerConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/config/RedisConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/config/SpspReceiverConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/stream/TrackingStreamReceiver.java
  connector-service-impl/src/main/java/org/interledger/connector/stream/TrackingStreamReceiverLinkFactory.java
  connector-service-impl/src/test/java/org/interledger/connector/stream/TrackingStreamReceiverLinkFactoryTest.java
Labels: cleanup, documentation
