Repository interledger4j/ilpv4-connector, pull requests merged in 2020-02, with the labels that each got.

#581 gracefully handle and log a peer that cannot be registered for ccp
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryExternalRoutingService.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/InMemoryExternalRoutingServiceTest.java
Labels: enhancement

#576 NPE in DefaultCcpSender
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpSender.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryExternalRoutingService.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/CcpSenderReceiverTest.java
  connector-server/pom.xml
Labels: bug, routing

#589 fix docker image that's broken due to missing spsp-core jar
  .circleci/config.yml
  connector-it/pom.xml
  connector-it/src/main/java/org/interledger/connector/it/markers/DockerImage.java
  connector-it/src/test/java/org/interledger/connector/it/ContainerHelper.java
  connector-it/src/test/java/org/interledger/connector/it/docker/JavaConnectorDockerImageIT.java
  connector-server/pom.xml
Labels: cleanup

#572 pub sub extravaganza
  connector-accounts/pom.xml
  connector-accounts/src/main/java/org/interledger/connector/accounts/event/AccountCreatedEvent.java
  connector-accounts/src/main/java/org/interledger/connector/accounts/event/AccountUpdatedEvent.java
  connector-admin-client/src/test/java/org/interledger/connector/client/ConnectorAdminClientTest.java
  connector-it/src/test/java/org/interledger/connector/it/AbstractIlpOverHttpIT.java
  connector-it/src/test/java/org/interledger/connector/it/ilpoverhttp/TwoConnectorMixedAssetCodeTestIT.java
  connector-pubsub-api/pom.xml
  connector-pubsub-api/src/main/java/org/interledger/connector/pubsub/AbstractCoordinatedEvent.java
  connector-pubsub-api/src/test/java/org/interledger/connector/pubsub/AbstractCoordinatedEventTest.java
  connector-pubsub-api/src/test/java/org/interledger/connector/pubsub/SampleCoordinatedEvent.java
  connector-pubsub/pom.xml
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationEventBusBridge.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationMessage.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationMessageIdGenerator.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationMessageIdGeneratorImpl.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationMessagePublisher.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationMessagePublisherImpl.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/CoordinationMessageSubscriber.java
  connector-pubsub/src/main/java/org/interledger/connector/pubsub/RedisPubSubConfig.java
  connector-pubsub/src/test/java/org/interledger/connector/pubsub/CoordinationEventBusBridgeTest.java
  connector-pubsub/src/test/java/org/interledger/connector/pubsub/CoordinationMessageIdGeneratorTest.java
  connector-pubsub/src/test/java/org/interledger/connector/pubsub/CoordinationMessagePublisherTest.java
  connector-pubsub/src/test/java/org/interledger/connector/pubsub/CoordinationSubscriberTest.java
  connector-pubsub/src/test/java/org/interledger/connector/pubsub/SampleCoordinatedEvent.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpSender.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/link/IlpOverHttpConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/link/LocalSpspFulfillmentConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/IdempotenceCacheConfig.java
  connector-server/src/main/resources/application-dev-secondary.yml
  connector-service-impl/pom.xml
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/balances/RedisBalanceTracker.java
  connector-service-impl/src/main/java/org/interledger/connector/config/BalanceTrackerConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/config/RedisConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/test/java/org/interledger/connector/accounts/DefaultAccountManagerTest.java
  connector-service-impl/src/test/java/org/interledger/connector/balances/AbstractRedisBalanceTrackerTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultNextHopPacketMapperTest.java
  pom.xml
  scripts/createPostgresDockerLocal.sh
Labels: accounts

#592 Move require32ByteSharedSecrets to EnabledFeatureSettings
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorParentChildIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java
  connector-model/src/main/java/org/interledger/connector/settings/EnabledFeatureSettings.java
  connector-server/src/main/resources/application-insecure.yml
  connector-server/src/main/resources/application.yml
  connector-server/src/test/resources/application-connector-unit-test.yml
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkSettingsValidator.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFile.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/EnabledFeatureSettingsFromPropertyFile.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsValidatorTest.java
  connector-service-impl/src/test/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFileTest.java
  connector-service-impl/src/test/resources/application-connector-unit-test.yml
Labels: configuration

#595 KMS clean up and make it easier to do encryption things
  connector-admin-client/src/main/java/org/interledger/connector/client/ConnectorAdminClient.java
  connector-crypto/connector-crypto-cli/pom.xml
  connector-crypto/connector-crypto-cli/src/main/java/org/interledger/connector/crypto/cli/shell/commands/EncryptionCommands.java
  connector-crypto/pom.xml
  connector-crypto/src/main/java/org/interledger/crypto/CryptoConfigConstants.java
  connector-crypto/src/main/java/org/interledger/crypto/EncryptionService.java
  connector-crypto/src/main/java/org/interledger/crypto/impl/DelegatingEncryptionService.java
  connector-crypto/src/main/java/org/interledger/crypto/impl/GcpEncryptionService.java
  connector-crypto/src/main/java/org/interledger/crypto/impl/JksEncryptionService.java
  connector-crypto/src/test/java/org/interledger/crypto/gcp/GcpEncryptionServiceTest.java
  connector-crypto/src/test/java/org/interledger/crypto/impl/DelegatingEncryptionServiceTest.java
  connector-it/src/test/resources/application.yml
  connector-model/src/main/java/org/interledger/connector/settings/GlobalRoutingSettings.java
  connector-model/src/test/java/org/interledger/connector/settings/ConnectorSettingsTest.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InMemoryExternalRoutingService.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/InMemoryExternalRoutingServiceTest.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/PathConstants.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/EncryptionController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/CryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/GcpCryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/crypto/JksCryptoConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SpringConnectorWebMvc.java
  connector-server/src/main/resources/application-gcp-kms.yml
  connector-server/src/main/resources/application-gcp-pubsub.yml
  connector-server/src/main/resources/application-insecure.yml
  connector-server/src/main/resources/application-jks.yml
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AbstractControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/EncryptionSpringBootTest.java
  connector-service-api/src/main/java/org/interledger/connector/crypto/ConnectorEncryptionService.java
  connector-service-impl/src/main/java/org/interledger/connector/crypto/DefaultConnectorEncryptionService.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkSettingsValidator.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/ConnectorKeyFromPropertyFile.java
  connector-service-impl/src/main/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFile.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsValidatorTest.java
  connector-service-impl/src/test/java/org/interledger/connector/settings/properties/ConnectorSettingsFromPropertyFileTest.java
  pom.xml
Labels: enhancement, security

#597 support JS "secretToken" scheme which is just like Bearer auth but without the "Bearer " prefix before the token.
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/BearerTokenSecurityContextRepository.java
  connector-server/src/test/java/org/interledger/connector/server/spring/auth/ilpoverhttp/BearerTokenSecurityContextRepositoryTest.java
Labels: accounts, security

#604 support using encrypted secret for spring.datasource.password
  connector-persistence/pom.xml
  connector-persistence/src/main/java/org/interledger/connector/persistence/config/ConnectorPersistenceConfig.java
  connector-persistence/src/main/java/org/interledger/connector/persistence/config/EncryptedDatasourcePasswordConfig.java
  connector-persistence/src/test/java/org/interledger/connector/persistence/config/EncryptedDatasourcePasswordConfigTest.java
Labels: security

#605 Fixes 593
  connector-service-impl/src/main/java/org/interledger/connector/fx/JavaMoneyUtils.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/main/java/org/interledger/connector/links/filters/DefaultLinkFilterChain.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitch.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChain.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/ExpiryPacketFilter.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultNextHopPacketMapperTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/filters/DefaultLinkFilterChainTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitchTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChainTest.java
Labels: balance-tracker, bug

#608 Update Quilt to v1.1.1
  pom.xml
Labels: dependencies
