Repository interledger4j/ilpv4-connector, pull requests merged in 2020-01, with the labels that each got.

#490 address pr comments #370
  connector-crypto/connector-crypto-cli/pom.xml
  pom.xml
Labels: configuration

#505 Df/extract admin client
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccountSettings.java
  connector-admin-client/pom.xml
  connector-admin-client/src/main/java/org/interledger/connector/client/ConnectorAdminClient.java
  connector-admin-client/src/test/java/org/interledger/connector/client/ConnectorAdminClientTest.java
  connector-server/pom.xml
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorAdminClient.java
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorAdminTestClient.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtHs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  pom.xml
Labels: accounts, dependencies, enhancement, v0.2.0

#502 Support for JWT RS256 for incoming authorization
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorParentChildIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/ilpoverhttp/TwoConnectorPeerIlpOverHttpTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-it/src/test/java/org/interledger/connector/it/AbstractIlpOverHttpIT.java
  connector-it/src/test/java/org/interledger/connector/it/ilpoverhttp/TwoConnectorIldcpTestIT.java
  connector-it/src/test/java/org/interledger/connector/it/ilpoverhttp/TwoConnectorIlpOverHttpPingTestIT.java
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/JwkRsaPublicKeyProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/JwtRs256AuthenticationProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/JwtRs256Configuration.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/Redactor.java
  connector-server/src/test/java/org/interledger/connector/server/JwksServer.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtHs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtRs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/SimpleIlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProviderTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/auth/ilpoverhttp/JwtRs256AuthenticationProviderTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/admin/AccountSettingsSpringBootTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/RedactorTest.java
  connector-service-impl/src/main/java/org/interledger/connector/DefaultILPv4Connector.java
  connector-service-impl/src/main/java/org/interledger/connector/accounts/DefaultAccountManager.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkSettingsValidator.java
  connector-service-impl/src/test/java/org/interledger/connector/accounts/DefaultAccountManagerTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsFactoryTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultLinkSettingsValidatorTest.java
  pom.xml
Labels: accounts, enhancement, security, v0.2.0

#509 Account Balance user endpoint
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/auth/ilpoverhttp/IlpOverHttpAuthenticationProvider.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/AccountBalanceController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/PathConstants.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/test/java/org/interledger/connector/server/client/ConnectorUserClient.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AccountBalanceSpringBootTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/ControllerTestConfig.java
  connector-service-api/src/main/java/org/interledger/connector/balances/AccountBalance.java
  connector-service-api/src/main/java/org/interledger/connector/balances/AccountBalanceResponse.java
  connector-service-impl/src/main/java/org/interledger/connector/balances/AccountBalanceService.java
  connector-service-impl/src/main/java/org/interledger/connector/config/BalanceTrackerConfig.java
  connector-service-impl/src/test/java/org/interledger/connector/balances/AbstractRedisBalanceTrackerTest.java
  connector-service-impl/src/test/java/org/interledger/connector/balances/AccountBalanceServiceTest.java
  pom.xml
Labels: accounts, balance-tracker, enhancement, v0.2.0

#522 Fixes for GH relocation
  README.md
  connector-it/src/test/java/org/interledger/connector/it/settlement/TwoConnectorXrpSettlementIT.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/PaymentRouter.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/admin/AccountsController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/swagger/README.md
  connector-service-impl/src/main/java/org/interledger/connector/balances/RedisBalanceTracker.java
  connector-service-impl/src/main/java/org/interledger/connector/config/CaffeineCacheConfig.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultLinkManager.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/main/java/org/interledger/connector/settlement/DefaultSettlementService.java
  pom.xml
Labels: documentation, v0.2.0

#528 Add endpoint to get metadata of controller at root url
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/MetaDataController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/model/ConnectorSettingsResponse.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/SecurityConfiguration.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/AbstractControllerTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/MetaDataControllerTest.java
Labels: configuration, v0.2.0

#530 Misc Enhancements (primary=tighten send receive routes logic)
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccountRelationship.java
  connector-accounts/src/main/java/org/interledger/connector/accounts/AccountSettings.java
  connector-accounts/src/test/java/org/interledger/connector/accounts/AccountSettingsTest.java
  connector-core/pom.xml
  connector-core/src/main/java/org/interledger/connector/core/Ilpv4Constants.java
  connector-crypto/src/main/java/org/interledger/crypto/ByteArrayUtils.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/AbstractTopology.java
  connector-it/src/main/java/org/interledger/connector/it/topologies/settlement/SimulatedXrplSettlementTopology.java
  connector-it/src/test/java/org/interledger/connector/it/ilpoverhttp/TwoConnectorMixedAssetCodeTestIT.java
  connector-it/src/test/java/org/interledger/connector/it/settlement/TwoConnectorXrpSettlementIT.java
  connector-jackson/src/test/java/org/interledger/connector/jackson/model/AccountSettingsJsonTest.java
  connector-routing-api/src/main/java/org/interledger/connector/routing/CcpSender.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultCcpReceiver.java
  connector-routing-impl/src/main/java/org/interledger/connector/routing/DefaultRouteBroadcaster.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/AbstractEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/JwtHs256IlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/converters/OerPreparePacketHttpMessageConverterTest.java
  connector-service-api/src/main/java/org/interledger/connector/links/NextHopPacketMapper.java
  connector-service-impl/src/main/java/org/interledger/connector/ConnectorExceptionHandler.java
  connector-service-impl/src/main/java/org/interledger/connector/fx/JavaMoneyUtils.java
  connector-service-impl/src/main/java/org/interledger/connector/links/DefaultNextHopPacketMapper.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitch.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/PeerProtocolPacketFilter.java
  connector-service-impl/src/main/java/org/interledger/connector/settlement/DefaultSettlementService.java
  connector-service-impl/src/test/java/org/interledger/connector/fx/JavaMoneyUtilsTest.java
  connector-service-impl/src/test/java/org/interledger/connector/links/DefaultNextHopPacketMapperTest.java
Labels: accounts, cleanup, enhancement, routing, v0.2.0

#540 Misc changes related to GCP and load testing
  connector-server/pom.xml
  connector-server/src/main/java/org/interledger/connector/server/ConnectorServerConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/gcp/GCPCloudLoggingJSONLayout.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/link/IlpOverHttpConfig.java
  connector-server/src/main/resources/logback-gcp.xml
Labels: balance-tracker, test-coverage, v0.2.0

#549 Wire problem-enabled ObjectMapper into IlpOverHttpLink
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/link/IlpOverHttpConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/web/JacksonConfig.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/SimpleIlpOverHttpEndpointTest.java
  connector-server/src/test/java/org/interledger/connector/server/ilpoverhttp/SimpleIlpOverHttpUnitTests.java
Labels: bug, v0.2.0

#552 Rename ConnectorKey and ConnectorKeys to CryptoKey and CryptoKeys
  connector-crypto/src/main/java/org/interledger/crypto/CryptoKey.java
  connector-crypto/src/main/java/org/interledger/crypto/CryptoKeys.java
  connector-model/src/main/java/org/interledger/connector/settings/ConnectorSettings.java
  connector-model/src/test/java/org/interledger/connector/settings/ConnectorSettingsTest.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorKeyFromPropertyFile.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/properties/ConnectorKeysFromPropertyFile.java
  connector-server/src/test/java/org/interledger/connector/server/spring/settings/ConnectorSettingsFromPropertyFileTest.java
  connector-service-impl/src/main/java/org/interledger/connector/crypto/DefaultConnectorEncryptionService.java
Labels: cleanup, v0.2.0

#551 Get rid of InterledgerAddressPrefix jackson modules
  connector-jackson/pom.xml
  connector-jackson/src/main/java/org/interledger/connector/jackson/ObjectMapperFactory.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/modules/InterledgerAddressPrefixDeserializer.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/modules/InterledgerAddressPrefixModule.java
  connector-jackson/src/main/java/org/interledger/connector/jackson/modules/InterledgerAddressPrefixSerializer.java
Labels: cleanup, v0.2.0

#555 Support application/ilp-octet-stream content-type
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/IlpHttpController.java
  connector-server/src/main/java/org/interledger/connector/server/spring/controllers/converters/OerPreparePacketHttpMessageConverter.java
  connector-server/src/test/java/org/interledger/connector/server/spring/controllers/IlpHttpControllerTest.java
Labels: v0.2.0

#564 don't match prefixes that are longer than the destination address
  connector-routing-impl/src/main/java/org/interledger/connector/routing/InterledgerAddressPrefixMap.java
  connector-routing-impl/src/test/java/org/interledger/connector/routing/InterledgerAddressPrefixMapTest.java
Labels: bug, routing

#566 track rejections in pubsub
  connector-server/src/main/java/org/interledger/connector/server/spring/gcp/GcpPubSubConfig.java
  connector-server/src/main/java/org/interledger/connector/server/spring/settings/SpringConnectorConfig.java
  connector-server/src/main/resources/application-gcp-pubsub.yml
  connector-service-api/src/main/java/org/interledger/connector/events/PacketEventPublisher.java
  connector-service-api/src/main/java/org/interledger/connector/events/PacketFullfillmentEvent.java
  connector-service-api/src/main/java/org/interledger/connector/events/PacketRejectionEvent.java
  connector-service-api/src/main/java/org/interledger/connector/gcp/FulfillmentPublisher.java
  connector-service-api/src/main/java/org/interledger/connector/gcp/GcpPacketResponseEvent.java
  connector-service-api/src/main/java/org/interledger/connector/gcp/GcpPacketResponseEventPublisher.java
  connector-service-impl/src/main/java/org/interledger/connector/ConnectorExceptionHandler.java
  connector-service-impl/src/main/java/org/interledger/connector/events/DefaultPacketEventPublisher.java
  connector-service-impl/src/main/java/org/interledger/connector/gcp/DefaultFulfillmentPublisher.java
  connector-service-impl/src/main/java/org/interledger/connector/gcp/DefaultGcpPacketResponseEventPublisher.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitch.java
  connector-service-impl/src/main/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChain.java
  connector-service-impl/src/test/java/org/interledger/connector/events/DefaultPacketEventPublisherTest.java
  connector-service-impl/src/test/java/org/interledger/connector/gcp/DefaultFulfillmentPublisherTest.java
  connector-service-impl/src/test/java/org/interledger/connector/gcp/DefaultGcpPacketResponseEventPublisherTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/DefaultILPv4PacketSwitchTest.java
  connector-service-impl/src/test/java/org/interledger/connector/packetswitch/filters/DefaultPacketSwitchFilterChainTest.java
Labels: balance-tracker, enhancement

#570 Make fxCache configurable. Defaults to 30s
  connector-core/src/main/java/org/interledger/connector/core/ConfigConstants.java
  connector-server/src/test/java/org/interledger/connector/server/javamoney/JavaMoneyConfigTest.java
  connector-service-impl/src/main/java/org/interledger/connector/config/CaffeineCacheConfig.java
Labels: configuration, fx
